fixed run script

diff --git a/docs/run b/docs/run
--- a/docs/run
+++ b/docs/run
@@ -2,12 +2,12 @@
 set -e
 
 RELEASES_URL="https://github.com/SeanLatimer/go-vanity-url/releases"
-FILE_BASENAME="goreleaser"
+FILE_BASENAME="go-vanity-url"
 
-test -z "$VERSION" && VERSION="$latest"
+test -z "$VERSION" && VERSION="latest"
 
 test -z "$VERSION" && {
-  echo "Unable to get goreleaser version." >&2
+  echo "Unable to get go-vanity-url version." >&2
   exit 1
 }
 
